ping:
  handler: ${self:custom.path.app}/handlers/utils/ping.handler
  description: Ping test
  timeout: 3
  reservedConcurrency: 1
  events:
    - httpApi:
        path: /v1/utils/ping
        method: GET

pingAuth:
  handler: ${self:custom.path.app}/handlers/utils/ping.handler
  description: Ping test with authentication
  timeout: 3
  reservedConcurrency: 1
  events:
    - httpApi:
        path: /v1/utils/ping/auth
        method: GET
        authorizer:
          name: firebaseJwtAuthorizer
