Resources:
  ElastiCacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "${self:provider.stackName}-elastiCacheSecurityGroup"
      GroupDescription: "Allow local inbound to ElastiCache port 11211, no outbound"
      SecurityGroupIngress:
        - CidrIp: 10.0.0.0/16
          IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 127.0.0.1/32
      VpcId:
        Ref: Vpc
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: "${self:provider.stackName}-elasticCacheSubnetGroup"
      Description: "Private ElastiCache subnet group"
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
  MemcachedCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: "${self:provider.stackName}-memcached"
      AutoMinorVersionUpgrade: true
      Engine: memcached
      CacheNodeType: cache.t2.micro
      NumCacheNodes: 1
      CacheSubnetGroupName:
        Ref: ElastiCacheSubnetGroup
      VpcSecurityGroupIds:
        - Ref: ElastiCacheSecurityGroup
