Resources:
  sampleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:provider.stackName}-sampleQueue
      VisibilityTimeout: 300 # 5min delay before next retry
      MessageRetentionPeriod: 43200 # 12h ttl in the queue
      RedrivePolicy:
        deadLetterTargetArn:
          'Fn::GetAtt':
            - SampleQueueDeadLetterQueue
            - Arn
        maxReceiveCount: 3 # max tries before pushing to DLQ

  SampleQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:provider.stackName}-sampleQueueDLQ
      MessageRetentionPeriod: 43200 # 12h ttl in the queue
